services:
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgresdev
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgres/data
  mongodb:
    image: mongo
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mongodev
    ports:
      - 27017:27017
    volumes:
      - mongodata:/var/lib/mongodb/data      
volumes:
  pgdata:   
  mongodata: 